[package]
name = "iykra-online-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
mongodb = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"
futures = "0.3"
dotenv = "0.15"